### ISSUE TITLE
Finish SignUp page

### ISSUE THREAD

**Issue by JustinO1055** [hunteroatway/CS372#15]
Is currently missing a few fields with the query hard coded with information. These fields need to be added, have validation done and then the query updated. Also need to implement file upload for the users avatar plus renaming of the file.

**Comment by subahturna** [comment]
Done.. 💯 :)

**Comment by JustinO1055** [comment]
Change the input for the DOB to a date style, this allows them to have a calendar, plus it converts the date to yyyy-mm-dd automatically for input into the database. current field does not allow that.
Avatar does not upload at all currently. Will need to upload it into the directory avatar with file name of (USERID).(FILE EXTENSION). Once it has been updated, it will have to be updated on the database with the value of "../avatar/(Uploaded file + extension).
Need server side validation for the other fields that have been added.
Does not appear to be any errors being printed by PHP. Was trying to sign up with a password with no uppercase letter and it would not work and would print no errors

**Comment by JustinO1055** [comment]
Input has for date has been changed. Will need to quickly modify the DB entry still, 
Avatar now uploads
API for location has been added
Need to add validation on client/ server side and print any errors to the user

**Comment by JustinO1055** [comment]
Needs to be tested to ensure that validation works and there is no errors. Once testing is complete the page is done.

**Comment by subahturna** [comment]
Added validation for avatar upload. Tested different scenarios. This page should be all good now.
