### ISSUE TITLE
Finish Posting Page

### ISSUE THREAD

**Issue by JustinO1055** [hunteroatway/CS372#16]
Need the additional fields pushed to github.
Need to combine it all with the PHP written.
Need to do form validation on all of the forms.
Need to do some error checking to ensure a user is logged in so they can post.

**Comment by hunteroatway** [comment]
Posting page has been completed. 
All additional fields have been added as specified in initial design. 
PHP has been implemented and is working good.
Form validation has been added.
Error checking for unlogged in users has been added
