### ISSUE TITLE
Posting Page Issues

### ISSUE THREAD

**Issue by hunteroatway** [hunteroatway/CS372#18]
Leave comments with specific issues with instructions on how to re-produce and what it causes for investigation.

**Comment by hunteroatway** [comment]
9781604501483 & 9781604501483 - don't exist in google books, return an empty JSON object and will not pull from the API

**Comment by hunteroatway** [comment]
TODO: 
- Non-existent books in the API need to be handled properly than just not working
- Fix JS validation error messages (ie: price field is not correctly handled)

**Comment by Hamza-Imtiaz** [comment]
These doesn't work as well 
ISBN:	0545385032
ISBN13:	9780545385039

**Comment by Hamza-Imtiaz** [comment]
TODO: 

- Add JS validation on autofill button so it will show the error right away (if the ISBN is not correct) instead of user need to click on submit.

![ISBN](https://user-images.githubusercontent.com/63941147/100700233-97b58780-3362-11eb-8806-34434a16bc9b.png)

**Comment by hunteroatway** [comment]
"These doesn't work as well when i try to auto fill them...
ISBN: 0545385032
ISBN13: 9780545385039

I can manually enter them and that works.."

-- This has been resolved with the latest commit. Tested both ISBN values. When the JSON object does not have a returned value that we try to retrieve it would throw an error in the console causing everything else to fail. These errors have now been handled.

**Comment by hunteroatway** [comment]
> These doesn't work as well when i try to auto fill them...
> ISBN: 0545385032
> ISBN13: 9780545385039
> 
> I can manually enter them and that works..

Trying to quote (see what this does) - Resolved

**Comment by hunteroatway** [comment]
Empty queries are fixed. JS validation messages still incorrect / not reset when input fields are updated with values.

**Comment by hunteroatway** [comment]
> TODO:
> 
> * Add JS validation on autofill button so it will show the error right away (if the ISBN is not correct) instead of user need to click on submit.
> 
> ![ISBN](https://user-images.githubusercontent.com/63941147/100700233-97b58780-3362-11eb-8806-34434a16bc9b.png)

JS validation is now on the auto-fill button, but currently does not clear after an empty query and then a successful query that fills the fields.

**Comment by hunteroatway** [comment]
> 9781604501483 & 9781604501483 - don't exist in google books, return an empty JSON object and will not pull from the API

Issue has been resolved. If an empty book is found, an error is displayed.

**Comment by hunteroatway** [comment]
All issues with validation, empty queries, and api not finding a book appear to be handled and resolved.
