### ISSUE TITLE
Message Page Issues

### ISSUE THREAD

**Issue by Hamza-Imtiaz** [hunteroatway/CS372#19]
Message is cutting out, If I try to message like "Let's be serious" it will only send "Let"

![message1](https://user-images.githubusercontent.com/63941147/100704526-478ef300-336b-11eb-9699-f472a222b1c3.png)
![message2](https://user-images.githubusercontent.com/63941147/100704528-478ef300-336b-11eb-8842-573d8807d651.png)

Need to fix this ^^

**Comment by JustinO1055** [comment]
Fixed issue with single quote. changes string conversion from js side to server side
