### ISSUE TITLE
Image Not Found

### ISSUE THREAD

**Issue by Patar221** [hunteroatway/CS372#20]
Created "Image Not Found" image for when API does not pull a cover. Please set it up to be set to this image in that case.

Image is called "imageNotFound" and is located in the images folder. Feel free to rename it.

**Comment by JustinO1055** [comment]
Added this in. Will need further testing. When tested please close the issue

**Comment by hunteroatway** [comment]
This appears to be working as tested. Tried with a couple different ISBN values and it appears to make that the cover and show up in the posting page fine.
