### ISSUE TITLE
Book not in API thus no isbn_13 values

### ISSUE THREAD

**Issue by JustinO1055** [hunteroatway/CS372#21]
If the book is not in the API, it can not autofill the hidden ISBN values. If this is the case, set ISBN_13 to the users inputted one, this will allow the book to be stored into the DB. If this is not set, the isbn_13 takes value of 0 and then books overlap.

**Comment by JustinO1055** [comment]
Added this in. Will need further testing. When tested please close the issue

**Comment by hunteroatway** [comment]
This appears to be working as implemented. Tested with a couple different ISBN's and they appear to update correctly depending on what information is missing.
This only happens if the user enters an ISBN that doesn't pull info, but submits using manual mode.
